version: 0.1
loglevel: debug
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  cache:
    blobdescriptor: inmemory
  delete:
    enabled: true
auth:
  token:
    realm: https://localhost:60443/realms/registry/protocol/docker-v2/auth
    service: registry-client
    issuer: https://localhost:60443/realms/registry
    rootcertbundle: /certs/bundle.crt
http:
  addr: 0.0.0.0:21000
  host: http://localhost:21000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
