version: '3.9'

services:

  registry:
    image: registry:2.8.1
    container_name: registry
    restart: unless-stopped
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./secrets/registry_htpasswd:/etc/docker/registry/htpasswd
      - data:/var/lib/registry
    ports:
      - 21000:21000
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  data:
