version: '3.9'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Postgres1234
      POSTGRES_DB: keyclock # Change this to required db
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker-networks

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: PGAdmin@1234
    ports:
      - 50000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  pg-data:
  pgadmin-data:
