version: '3.9'

services:
  mongo:
    image: mongo:5
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    command: >
      --replSet mReplSet
      --bind_ip localhost,mongo
      --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAdmin12
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db
      - ./secrets/mongo-replication.key:/etc/mongo-replication.key
    ports:
      - 10001:27017
    networks:
      - docker-networks

  mongo-1:
    image: mongo:5
    container_name: mongo-1
    hostname: mongo-1
    restart: unless-stopped
    command: >
      --replSet mReplSet
      --bind_ip localhost,mongo-1
      --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAdmin12
    volumes:
      - mongo-1-config:/data/configdb
      - mongo-1-data:/data/db
      - ./secrets/mongo-replication.key:/etc/mongo-replication.key
    ports:
      - 10002:27017
    depends_on:
      - mongo
    networks:
      - docker-networks

  mongo-2:
    image: mongo:5
    container_name: mongo-2
    hostname: mongo-2
    restart: unless-stopped
    command: >
      --replSet mReplSet
      --bind_ip localhost,mongo-2
      --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAdmin12
    volumes:
      - mongo-2-config:/data/configdb
      - mongo-2-data:/data/db
      - ./secrets/mongo-replication.key:/etc/mongo-replication.key
    ports:
      - 10003:27017
    depends_on:
      - mongo
    networks:
      - docker-networks

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: on-failure
    environment:
      NODE_OPTIONS: --unhandled-rejections=strict
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false # Change to true for admin db
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: MongoDB@1234
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: MongoAdmin12
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: monokai
        # https://codemirror.net/5/demo/theme.html
    ports:
      - 10000:8081
    depends_on:
      - mongo
      - mongo-1
      - mongo-2
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  mongo-config:
  mongo-data:
  mongo-1-config:
  mongo-1-data:
  mongo-2-config:
  mongo-2-data:
