version: '3.9'

services:
  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    hostname: newrelic-infra
    restart: unless-stopped
    environment:
      NRIA_LICENSE_KEY: YOUR_LICENSE_KEY # License Key
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock