version: '3.9'

services:

  redis:
    image: redis:7.0.4
    container_name: redis
    hostname: redis
    restart: unless-stopped
     # Username is 'default'
     # Password is 'Redis@123456'
    command: >
      --requirepass Redis@123456
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - docker-networks

  redisinsight:
    image: redislabs/redisinsight:1.13.0
    container_name: redisinsight
    hostname: redisinsight
    restart: unless-stopped
    ports:
      - 40000:8001
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  redis-data:
  redisinsight-data:
