version: '3.9'

services:
  keycloak:
    build: .
    image: keycloak:19.0.1-local
    container_name: keycloak
    restart: on-failure
    command: >
      start
        --optimized
        --hostname=localhost
        --https-port=60443
        --db-username=admin
        --db-password=Postgres1234
        --db-url=jdbc:postgresql://postgres:5432/keycloak
        --https-certificate-file=/certs/server.crt
        --https-certificate-key-file=/certs/server.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Keycloak@123
    volumes:
      - ./certs:/certs
    ports:
      - 60443:60443
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks
