services:
  jupyter:
    image: nvidia/cuda:12.1.0-runtime-ubuntu22.04
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COND_LINK: https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh
    runtime: nvidia
    user: root
    volumes:
      - "./notebooks:/notebooks"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES compute,utility
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
