services:
  tensorflow:
    container_name: tensorflow
    image: nvcr.io/nvidia/tensorflow:23.10-tf2-py3
    runtime: nvidia
    restart: unless-stopped
    command: >
      jupyter lab
      --ip 0.0.0.0
      --allow-root
      --no-browser
      --autoreload
    network_mode: bridge
    environment:
      - JUPYTER_TOKEN=dockertoken
      - RESTARTABLE=yes
      - TF_GPU_ALLOCATOR=cuda_malloc_async
      - TF_CPP_MIN_LOG_LEVEL=2
    volumes:
      - jupyter-data:/root/.jupyter
      - keras-data:/root/.keras
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    shm_size: 1gb
    ipc: host
    privileged: true
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - 80:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  jupyter-data:
  keras-data:
