version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:2.15.1
    container_name: portainer
    command: >
      --http-disabled
      --sslcert /certs/server.crt
      --sslkey /certs/server.key
      --admin-password-file /secrets/password
    restart: unless-stopped
    volumes:
      - ./certs:/certs
      - ./secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - 39443:9443
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  data:
