version: '3.9'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MysqlRoot@12
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Mysql12345
      MYSQL_DATABASE: mydb
    restart: on-failure
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - docker-networks

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: unless-stopped
    ports:
      - 18000:8080
    depends_on:
      - mysql
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  data:
