version: '3.9'

services:
  roach:
    image: cockroachdb:v22.1.6-local
    container_name: cockroachdb
    hostname: roach
    build:
      context: Dockerfiles
      dockerfile: roach.dockerfile
    environment:
      NODE_HOSTNAME: roach
    command: >
      start
        --certs-dir=certs
        --cache=.25
        --max-sql-memory=.25
        --cluster-name=roach-intrusion
        --join=roach,roach-1,roach-2
    restart: on-failure
    volumes:
      - roach-data:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 20000:8080
    networks:
      - docker-networks

  roach-1:
    image: cockroachdb:v22.1.6-local
    container_name: cockroachdb-1
    hostname: roach-1
    environment:
      NODE_HOSTNAME: roach-1
    command: >
      start
        --certs-dir=certs
        --cache=.25
        --max-sql-memory=.25
        --cluster-name=roach-intrusion
        --join=roach,roach-1,roach-2
    restart: on-failure
    volumes:
      - roach-1-data:/cockroach/cockroach-data
    depends_on:
      - roach
    networks:
      - docker-networks

  roach-2:
    image: cockroachdb:v22.1.6-local
    container_name: cockroachdb-2
    hostname: roach-2
    environment:
      NODE_HOSTNAME: roach-2
    command: >
      start
        --certs-dir=certs/
        --cache=.25
        --max-sql-memory=.25
        --cluster-name=roach-intrusion
        --join=roach,roach-1,roach-2
    restart: on-failure
    volumes:
      - roach-2-data:/cockroach/cockroach-data
    depends_on:
      - roach
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  roach-data:
  roach-1-data:
  roach-2-data:
  roach-3-data:
