version: '3.9'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Postgres1234
      POSTGRES_DB: keycloak # Change this to required db name
    command: >
      -c ssl=on -c ssl_cert_file=/certs/server.crt -c ssl_key_file=/certs/server.key
    restart: unless-stopped
    volumes:
      - ./certs:/certs
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker-networks

  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: PGAdmin@1234
      PGADMIN_ENABLE_TLS: True
    ports:
      - 50443:443
    volumes:
      - ./certs/pga-server.crt:/certs/server.cert
      - ./certs/pga-server.key:/certs/server.key
      - admin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  data:
  admin_data:
