version: '3.9'

services:

  redis:
    image: redis:7.0.4
    container_name: redis
    restart: unless-stopped
    privileged: true
    command: >
      /etc/redis/redis.conf
      --tls-port 6379
    volumes:
      - ./certs:/certs
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - docker-networks

  redisinsight:
    image: redislabs/redisinsight:1.13.0
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - 40000:8001
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis
    networks:
      - docker-networks

networks:
  docker-networks:
    name: docker-networks

volumes:
  redis-data:
  redisinsight-data:
